# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc7c141680e111e24b91fa8f431940f4537d52d7186dbb28e6bec4660cf5d2f44679f1675ee31ebe3580d3e9a0d33536c8bbe911a0b8fe08be51c2ade95d1f90

test:
  secret_key_base: 0af6c6e4840dc8807068f49cabec25132de00380b2578f882bb71f4fc3b9c05044af2e6fb91858ed97b29d3fd7ebf0d67876bc43aa60a8762bae9db25bd03c4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
